# @package _global_
config:
  VERBOSE: True
  LOG_FREQUENCY: 500
  TEST_ONLY: False
  TEST_MODEL: True
  TEST_EVERY_NUM_EPOCH: 4
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  TENSORBOARD_SETUP:
    USE_TENSORBOARD: true
  CHECKPOINT:
    DIR: "simclr_spatial_resnet18_fuzzy_swappedon_SineGrating2019_lw0_linear_eval_checkpoints"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 4 # in units of epochs
  DATA:
    NUM_DATALOADER_WORKERS: 8
    TRAIN:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      DATA_PATHS: ["/data5/chengxuz/imagenet_raw/train"]
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
    TEST:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      DATA_PATHS: ["/data5/chengxuz/imagenet_raw/validation"]
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      SHOULD_FLATTEN_FEATS: False
    TRUNK:
      NAME: custom_resnet
      TRUNK_PARAMS:
        VisslResNet:
          ARCH: resnet18
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 512, "dims": [512, 1000]}]
      ]
    WEIGHTS_INIT:
      PARAMS_FILE: "/mnt/fs6/eshedm/spacetorch/vissl_checkpoints/simclr_spatial_resnet18_fuzzy_swappedon_SineGrating2019_lw0_checkpoints/model_final_checkpoint_phase199.torch"
      STATE_DICT_KEY_NAME: classy_state_dict
    SYNC_BN_CONFIG:
        CONVERT_BN_TO_SYNC_BN: True
        SYNC_BN_TYPE: pytorch
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
  OPTIMIZER:
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
    num_epochs: 28
    nesterov: True
    regularize_bn: False
    regularize_bias: True
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_value: 0.01
          base_lr_batch_size: 256
        name: multistep
        values: [0.01, 0.001, 0.0001, 0.00001]
        milestones: [8, 16, 24]
        update_interval: epoch
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 4 # 2 GPUs
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
