# @package _global_
config:
  CHECKPOINT:
    DIR: "/data3/eshedm/spacetorch/checkpoints/supervised_resnet18_lw0_checkpoints"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 5 # in units of epochs
  DATA:
    NUM_DATALOADER_WORKERS: 4
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      DATA_PATHS: ["/data/chengxuz/Dataset/imagenet_raw/train"]
      LABEL_SOURCES: [disk_folder]
      LABEL_TYPE: standard # for supervised learning
      BATCHSIZE_PER_REPLICA: 128
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.4
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      DATA_SOURCES: [disk_folder]
      DATA_PATHS: ["/data/chengxuz/Dataset/imagenet_raw/validation"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 128 
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: custom_resnet
      TRUNK_PARAMS:
        VisslResNet:
          ARCH: resnet18
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [512, 1000]}],
      ]
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
  OPTIMIZER:
    name: sgd
    use_larc: False
    weight_decay: 0.000001
    momentum: 0.9
    nesterov: True
    num_epochs: 200
    regularize_bn: False
    regularize_bias: True
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_value: 0.3
          base_lr_batch_size: 256
        name: cosine
        start_value: 0.15   # LR for batch size 256
        end_value: 0.0000
        update_interval: step
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 4
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  VERBOSE: True
  LOG_FREQUENCY: 500
  TEST_ONLY: False
  TEST_MODEL: True
  SEED_VALUE: 0
  TEST_EVERY_NUM_EPOCH: 5
  TENSORBOARD_SETUP:
    USE_TENSORBOARD: true
