model:
  model_config:
    TRUNK:
      NAME: spatial_resnet18
      TRUNK_PARAMS:
        position_dir: simclr_spatial_resnet18_fuzzy_swappedon_SineGrating2019_lw0/resnet18_retinotopic_init_fuzzy_swappedon_SineGrating2019_NBVER2
  name: SpatialResNet18
  weights:
    checkpoint_dir: checkpoints/white_noise_training_checkpoints
    step: latest
name: white_noise_trained
