name: supervised_resnet18_chanx2
model:
  name: ResNet18_ChanX
  model_config:
    TRUNK:
      TRUNK_PARAMS:
        channel_multiplier:
          - 1
          - 2
          - 1
          - 1
    HEAD:
      PARAMS_MULTIPLIER: 1.0
      DIMS: [512, 1000]
  weights:
    checkpoint_dir: "vissl_checkpoints/resnet18_chanx2_supervised_checkpoints"
    step: latest
  layers:
    - "layer1.0"
    - "layer1.1"
    - "layer2.0"
    - "layer2.1"
    - "layer3.0"
    - "layer3.1"
    - "layer4.0"
    - "layer4.1"
initial_position_dir: "resnet18_chanx2_retinotopic_init"
swapopt:
  num_steps: 100000000
  steps_per_neighborhood: 500
